[package]
name = "lib3mf-sys"
version = "0.1.0"
edition = "2021"
links = "3mf"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"

[build-dependencies]
cmake = "0.1.48"
pkg-config = "0.3.25"
vcpkg = "0.2.15"
